version: '3'

services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: neobis_project8_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  spring_boot_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/neobis_project8_auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8081
      JWT_SECRET: my-secret-key
      JWT_LIFETIME: 30m
    depends_on:
      - postgres_db